### ISSUE TITLE
Update the framework for jet-variables

### ISSUE THREAD

**Issue by AlessandroTarabini** [bonanomi/FiducialXSFWK#10]

**Comment by bonanomi** [comment]
Currently under test measurement for `nJets`. Variables currently used:

    obs_reco = 'nCleanedJetsPt30'
    obs_gen  = 'nCleanedGenJetPt30'

In both cases cleaned jets with pT > 30 GeV are considered. `nCleanedGenJetPt30` newly introduced in the skimmer.
Check also for pT leading jet. All the variables are available in CJLST framework. Possibly need a new round of production to include them in final TTrees, otherwise need to extend skim_MC.

Implement properly JES in `RunCoefficients` propagate through the rest of the code.

**Comment by AlessandroTarabini** [comment]
GEN jets variables BBF-style included in CJLST (framework already updated, committed, and tested -> https://github.com/AlessandroTarabini/ZZAnalysis/tree/Run2_CutBased_BTag16_BBF)

**Comment by bonanomi** [comment]
Done. See [this pull request](https://github.com/bonanomi/FiducialXSFWK/commit/4d2092d6322d5ec3fc1cf3ed5bfa4e25d780b4a0)
